### ISSUE TITLE
Invalid character 's'

### ISSUE THREAD

**Issue by falbuixech** [AbdBarho/stable-diffusion-webui-docker#336]
**Has this issue been opened before?**

- [X] It is not in the [FAQ](https://github.com/AbdBarho/stable-diffusion-webui-docker/wiki/FAQ), I checked.
- [X] It is not in the [issues](https://github.com/AbdBarho/stable-diffusion-webui-docker/issues?q=), I searched. Theres actually  one, closed without info,

**Describe the bug**

After: _docker compose --profile auto up --build_

I get:

```
 => [stage-2  9/14] RUN --mount=type=cache,target=/root/.cache/pip   19.7s
 => [stage-2 10/14] RUN --mount=type=cache,target=/root/.cache/pip   14.3s
 => [stage-2 11/14] RUN --mount=type=cache,target=/root/.cache/pip    9.6s
 => [stage-2 12/14] COPY . /docker                                    0.1s
 => [stage-2 13/14] RUN <<EOF (python3 /docker/info.py /stable-diffu  0.6s
 => [stage-2 14/14] WORKDIR /stable-diffusion-webui                   0.1s
 => exporting to image                                               13.7s
 => => exporting layers                                              13.7s
 => => writing image sha256:e6ebf8a6174ce28996d27c966c2a27a3007d47c6  0.0s
 => => naming to docker.io/library/sd-auto:45                         0.0s
[+] Running 1/1
 - Container webui-docker-auto-1  Created                             0.2s
Attaching to webui-docker-auto-1
webui-docker-auto-1  | Mounted .cache
webui-docker-auto-1  | Mounted LDSR
webui-docker-auto-1  | mkdir: created directory '/data/BLIP'
webui-docker-auto-1  | Mounted BLIP
webui-docker-auto-1  | mkdir: created directory '/data/Hypernetworks'
webui-docker-auto-1  | Mounted Hypernetworks
webui-docker-auto-1  | Mounted VAE
webui-docker-auto-1  | Mounted GFPGAN
webui-docker-auto-1  | Mounted RealESRGAN
webui-docker-auto-1  | Mounted Deepdanbooru
webui-docker-auto-1  | Mounted ScuNET
webui-docker-auto-1  | Mounted .cache
webui-docker-auto-1  | Mounted StableDiffusion
webui-docker-auto-1  | Mounted embeddings
webui-docker-auto-1  | Mounted ESRGAN
webui-docker-auto-1  | Mounted config.json
webui-docker-auto-1  | Mounted SwinIR
webui-docker-auto-1  | Mounted Lora
webui-docker-auto-1  | Mounted MiDaS
webui-docker-auto-1  | Mounted ui-config.json
webui-docker-auto-1  | Mounted BSRGAN
webui-docker-auto-1  | Mounted Codeformer
webui-docker-auto-1  | mkdir: created directory '/data/config/auto/extensions'
webui-docker-auto-1  | Mounted extensions
webui-docker-auto-1  | + python -u webui.py --listen --port 7860 --allow-code --medvram --xformers --enable-insecure-extension-access --api
webui-docker-auto-1  | Removing empty folder: /stable-diffusion-webui/models/BSRGAN
webui-docker-auto-1  | Calculating sha256 for /stable-diffusion-webui/models/Stable-diffusion/sd-v1-5-inpainting.ckpt: c6bbc15e3224e6973459ba78de4998b80b50112b0ae5b5c67113d56b4e366b19
webui-docker-auto-1  | Loading weights [c6bbc15e32] from /stable-diffusion-webui/models/Stable-diffusion/sd-v1-5-inpainting.ckpt
webui-docker-auto-1  | Creating model from config: /stable-diffusion-webui/configs/v1-inpainting-inference.yaml
webui-docker-auto-1  | LatentInpaintDiffusion: Running in eps-prediction mode
invalid character 's' looking for beginning of value
```

**Which UI**

auto

**Hardware / Software**

- OS: Windows 10 Pro
- OS version:  22H2 19045.2604
- WSL version (if applicable): 2
- Docker Version: 20.10.22
- Docker compose version: v2.15.1
- RAM: 32GB
- GPU/VRAM: RTX3080 10GB

**Steps to Reproduce**

After: _docker compose --profile auto up --build_
I get: [...] invalid character 's' looking for beginning of value`

![imagen](https://user-images.githubusercontent.com/52744571/219903306-696bef47-8774-4e1f-a02d-b9654a1e69a2.png)

**Comment by AbdBarho** [comment]
it seems there is a typo in the config being read?

I just pushed an update to master, can you try it again if it works? otherwise we would need to debug this better.

**Comment by falbuixech** [comment]
Same error. After: _docker compose --profile auto up --build_

I still get: 

`webui-docker-auto-1  | Creating model from config: /stable-diffusion-webui/configs/v1-inpainting-inference.yaml
webui-docker-auto-1  | LatentInpaintDiffusion: Running in eps-prediction mode
webui-docker-auto-1  | DiffusionWrapper has 859.54 M params.
Downloading (…)olve/main/vocab.json:   0%|          | 0.00/961k [00:00<?, ?Downloading (…)olve/main/vocab.json: 100%|██████████| 961k/961k [00:00<00:0Downloading (…)olve/main/vocab.json: 100%|██████████| 961k/961k [00:00<00:00, 1.55MB/s]
Downloading (…)olve/main/merges.txt:   0%|          | 0.00/525k [00:00<?, ?Downloading (…)olve/main/merges.txt: 100%|██████████| 525k/525k [00:00<00:0Downloading (…)olve/main/merges.txt: 100%|██████████| 525k/525k [00:00<00:00, 912kB/s]
Downloading (…)cial_tokens_map.json:   0%|          | 0.00/389 [00:00<?, ?BDownloading (…)cial_tokens_map.json: 100%|██████████| 389/389 [00:00<00:00, 210kB/s]
Downloading (…)okenizer_config.json:   0%|          | 0.00/905 [00:00<?, ?BDownloading (…)okenizer_config.json: 100%|██████████| 905/905 [00:00<00:00, 648kB/s]
Downloading (…)lve/main/config.json:   0%|          | 0.00/4.52k [00:00<?, Downloading (…)lve/main/config.json: 100%|██████████| 4.52k/4.52k [00:00<00:00, 3.25MB/s]
invalid character 's' looking for beginning of value`

**Comment by AbdBarho** [comment]
might be related

https://github.com/docker/for-mac/issues/6575

https://austindewey.com/2020/12/11/troubleshooting-invalid-character-looking-for-beginning-of-value/

it seems to be a docker problem, did you just install docker recently? some suggested that restarting your PC could solve the problm.

**Comment by falbuixech** [comment]
Installed yesterday, rebooted many times. Reinstalled today, rebooted at least  2 times. I've seen that thread before opening this one, but it seems unresolved if I understand correctly.

**Comment by AbdBarho** [comment]
This is weird, I have played around and could not re-produce the error. I basically have the same setup & versions with the exception of windows 10 home.

You can try downgrading docker if you want to, but my gut feeling is that it won't change anything.

Perhaps one last thing that we did not check are the nvidia drivers, but I assume they are already up-to-date.

**Comment by falbuixech** [comment]
Yep, so weird. I don't think the difference between Home and Pro is relevant. 

Which version of Docker are you running? Same as me?

Not at home now to tell you the exact version, but yes, Nvidia drivers are up to date.

**Comment by falbuixech** [comment]
Solved! Updating pip from whatever version I was in, to pip 23.0.1. Maybe its worth asking for the pip version in the _Hardware / Software_ for future problems. Thanks for your help!
